### ISSUE TITLE
JSON escaping does not work as expected

### ISSUE THREAD

**Issue by wietse-postfix** [sys4/tlsrpt#12]
The tlsrpt library has an internal library function  `json_escape()` function to convert bytes that are written to a JSON string (text between double quotes).

It implements the following mapping:

All byte values have an identity mapping except: 

- Prepend `\` to double quote (correct)
- Prepend `\` to `\` (correct)
- `a` becomes `A` (incorrect)

The main issue is that a control character is written unchanged. This includes line breaks and other badness that are not allowed in a JSON string (Postfix should not send line breaks and so on to the library, but it is better to do this right). 

To fix, control characters (including nul and del) need to be escaped, and the false `a` to `A` mapping needs to be undone.

References:

- [RFC  8259 section 7](https://datatracker.ietf.org/doc/html/rfc8259#section-7) lists whart characters need escaping. It can be a confusing read.

- There is a nicer diagram in https://stackoverflow.com/questions/19176024/how-to-escape-special-characters-in-building-a-json-string.

- [Postfix quote_for_json.c](https://github.com/vdukhovni/postfix/blob/master/postfix/src/util/quote_for_json.c) seems to be consistent with the above.

**Comment by BLohner** [comment]
The a to A mapping is a remnant that unfortunately survived from very early testing.
This will get fixed in the code creating the mapping table.

**Comment by wietse-postfix** [comment]
The current implementation still does not convert control characters as required by JSON. This is now a blocker for Postfix release of TLSRPT support. 

 The libtlsrpt mapping table goes like like this:

```
const char *tlsrpt_json_escape_values[256]={
 "\x00", "\x01", "\x02", "\x03", "\x04", "\x05", "\x06", "\x07",
 "\x08", "\x09", "\x0a", "\x0b", "\x0c", "\x0d", "\x0e", "\x0f",
 "\x10", "\x11", "\x12", "\x13", "\x14", "\x15", "\x16", "\x17",
 "\x18", "\x19", "\x1a", "\x1b", "\x1c", "\x1d", "\x1e", "\x1f",
 ...
 "x", "y", "z", "{", "|", "}", "~", "\x7f",
 ...};
```
As before, the only non-identity mappings are prepending \ to \ and ".

Thus, it still maps control character values 0 ..31 and 127 (DEL) to the exact same values 0..31 and 127. That is incorrect.

Among other errors this mapping results in broken JSON when a string value contains <CR><LF>. These will appear in TLSRPT reports as part of the server EHLO response. Here is an example of such broken JSON:
```
{"d": "porcupine.org","pr": "v=TLSRPTv1;ruA=mAilto:smtp-tls-reports@porcupine.org"
,"policies":[{"policy-type":2,"policy-string":["s1","s2"],"mx-host":["p1","p2"],"failure-details":[{"c":205,"s": "192.168.86.150","n": "m1.porcupine.org","h": "250-m1.porcupine.org
250-PIPELINING
250-SIZE 52428800
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-SMTPUTF8
250 CHUNKING","r": "168.100.3.73","f": "self-signed_certificAte"}],"t":1,"f":1}]}
```

**Comment by BLohner** [comment]
I see...
I have committed a new version that escapes values 0..31 and 127.

Changes to libtlsrpt:
- bugfix: fixed JSON escaping
- extend error description: tlsrpt_strerror description includes the libtlsrpt function name in all cases
- API extension: added new function tlsrpt_get_sock() to give access to the socket file descriptor to allow tuning of SO_SNDBUF socket ooption. Note: Increasing SO_SNDBUF alone ist not sufficient to fully buffer bursts, also /proc/sys/net/unix/max_dgram_qlen needs to be increased to make use of the enlarged buffer.

**Comment by wietse-postfix** [comment]
This version of the JSON string encoder is more correct: there are no unencoded line breaks in the server's EHLO response. Below are the contents of an UDP datagram that the TLSRPT client library sends:
```
{"d": "porcupine.org","pr": "v=TLSRPTv1;rua=mailto:smtp-tls-reports@porcupine.org"
,"policies":[{"policy-type":2,"policy-string":["s1","s2"],"mx-host":["p1","p2"],"failure-details":[{"c":203,"s": "192.168.86.150","n": "m1.porcupine.org","h": "250-m1.porcupine.org\u000d\u000a250-PIPELINING\u000d\u000a250-SIZE 52428800\u000d\u000a250-ETRN\u000d\u000a250-STARTTLS\u000d\u000a250-ENHANCEDSTATUSCODES\u000d\u000a250-8BITMIME\u000d\u000a250-SMTPUTF8\u000d\u000a250 CHUNKING","r": "168.100.3.73"}],"t":1,"f":1}]}
``
Instead of the expected \r\n, the line breaks are emitted as \u000d\u000. Although technically correct, it makes the JSON a lttle harder to read for a human reviewer, but every decent JSON parser implementation will handle it.  It would be nice if this could emit the "usual" backslash sequences i.e. \b, \f, \r, \n, \t for the common control characters that have such a representation, but it is not a deal breaker.

**Comment by wietse-postfix** [comment]
Peaking of nice to have, it would be nice if the TLSRPT client library can send a datagram without a  line break between the closing quote of the TLRPT policy string,  and  the comma before "policies". It just does not look good.

**Comment by BLohner** [comment]
Newest commit uses the "usual" backslash sequences for  \b, \f, \r, \n, \t.

Additionally, it no longer puts line breaks into the datagrams.

**Comment by wietse-postfix** [comment]
Confirmed!

**Comment by wietse-postfix** [comment]
Example library output for success:

```
{"d": "sys4.de","pr": "v=TLSRPTv1; rua=mailto:smtp-tls-report@sys4.de","policies":[{"policy-type":1,"policy-domain": "mail.sys4.de","policy-string":["3 1 1 236831AEEAB41E7BD10DC14320600B245C791B338121383D5A2916F7EF97B49B"],"t":0,"f":0}]}
```

And example output for failure:

```
{"d": "porcupine.org","pr": "v=TLSRPTv1;rua=mailto:smtp-tls-reports@porcupine.org","policies":[{"policy-type":2,"policy-string":["s1","s2"],"mx-host":["p1","p2"],"failure-details":[{"c":205,"s": "168.100.3.7","n": "spike.porcupine.org","h": "250-spike.porcupine.org\r\n250-PIPELINING\r\n250-SIZE 52428800\r\n250-ETRN\r\n250-STARTTLS\r\n250-ENHANCEDSTATUSCODES\r\n250-8BITMIME\r\n250-SMTPUTF8\r\n250 CHUNKING","r": "168.100.3.2","f": "self-signed_certificate"}],"t":1,"f":1}]}
```

```

**Comment by BLohner** [comment]
That looks indeed fine.
